site_name: T3CO-2
site_description: Transportation Technology Total Cost of Ownership
repo_url: https://github.com/NREL/T3CO/tree/t3co-2.0
edit_uri: https://github.com/NREL/T3CO/tree/t3co-2.0/docs
site_author: Harish Panneer Selvam 

extra_css:
  - https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css
  - stylesheets/extra.css
extra_javascript:
  - https://code.jquery.com/jquery-3.6.0.min.js
  - https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js
  - stylesheets/datatables.js 

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_if_no_docstring: true
            docstring_options:
              ignore_init_summary: false
            merge_init_into_class: false
            heading_level: 2
            show_root_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_toc_entry: true 
            annotations_path: source
            show_signature: true
            separate_signature: false
            show_signature_annotations: true
            unwrap_annotated: true

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences


theme:
  name: material
  favicon: t3co_logo.svg
  highlightjs: true
  hljs_languages:
    - python
    - yaml
  features:
    - search.highlight
    - content.action.view
    - search.suggest
    - content.code.copy
    - navigation.path
    - content.tooltips

  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye

nav:
    - Home: index.md
    - Installation: installation.md
    - Quick Start: quick_start.md
    - Overview: T3CO_Overview.md
    - Inputs: 
      - Vehicle: pages/vehicle_inputs_descriptions.md
      - Scenario: pages/scenario_inputs_descriptions.md
      - Config: pages/config_inputs_descriptions.md
    - Outputs:
      - Ledger: pages/ledger_outputs_descriptions.md
    - API Reference: 
      - Input Data SubModules:
        - Vehicle: modules/vehicle.md
        - Scenario: modules/scenario.md
        - Config: modules/config.md  
      - Energy SubModules:
        - Energy: modules/energy.md
        - FASTSim Wrapper: modules/fastsim_wrapper.md
      - Cost SubModules:
        - Capital Costs: modules/capital_costs.md
        - Operating Costs: modules/operating_costs.md
        - Opportunity Costs: modules/opportunity_costs.md
      - TCO SubModules:
        - TCO Calc Per Year: modules/tcocalc.md
        - Ledger: modules/ledger.md
      - CLI SubModules:
        - Sweep: modules/sweep.md
      - Utility SubModules:
        - Demo Files Installer: modules/demo_files_installer.md
        - Print Class Objects: modules/print_class_objects.md
